-- Mesure anonyme de la visibilité du site (aucune donnée personnelle).
CREATE TABLE IF NOT EXISTS public.analytics_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name text NOT NULL CHECK (event_name IN ('page_view', 'click')),
  visitor_id text NOT NULL,
  session_id text NOT NULL,
  page_path text NOT NULL,
  target_path text,
  source text NOT NULL DEFAULT 'direct' CHECK (source IN ('direct', 'google', 'ai', 'social', 'other')),
  source_detail text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS analytics_events_created_at_idx ON public.analytics_events (created_at DESC);
CREATE INDEX IF NOT EXISTS analytics_events_source_idx ON public.analytics_events (source, created_at DESC);
CREATE INDEX IF NOT EXISTS analytics_events_page_idx ON public.analytics_events (page_path, created_at DESC);

ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can record analytics events"
  ON public.analytics_events FOR INSERT
  TO anon, authenticated
  WITH CHECK (
    event_name IN ('page_view', 'click')
    AND char_length(visitor_id) BETWEEN 1 AND 100
    AND char_length(session_id) BETWEEN 1 AND 100
    AND char_length(page_path) BETWEEN 1 AND 500
  );

CREATE OR REPLACE FUNCTION public.get_visibility_stats(p_since timestamptz)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  result jsonb;
  source_rows jsonb;
  page_rows jsonb;
  click_rows jsonb;
  daily_rows jsonb;
BEGIN
  SELECT COALESCE(jsonb_agg(to_jsonb(grouped) ORDER BY grouped.views DESC), '[]'::jsonb)
  INTO source_rows
  FROM (
    SELECT source AS name,
      count(*) FILTER (WHERE event_name = 'page_view')::int AS views,
      count(DISTINCT visitor_id) FILTER (WHERE event_name = 'page_view')::int AS visitors
    FROM analytics_events
    WHERE created_at >= p_since
    GROUP BY source
  ) grouped;

  SELECT COALESCE(jsonb_agg(to_jsonb(grouped) ORDER BY grouped.views DESC), '[]'::jsonb)
  INTO page_rows
  FROM (
    SELECT page_path AS name,
      count(*) FILTER (WHERE event_name = 'page_view')::int AS views,
      count(*) FILTER (WHERE event_name = 'click')::int AS clicks
    FROM analytics_events
    WHERE created_at >= p_since
    GROUP BY page_path
    ORDER BY views DESC
    LIMIT 20
  ) grouped;

  SELECT COALESCE(jsonb_agg(to_jsonb(grouped) ORDER BY grouped.clicks DESC), '[]'::jsonb)
  INTO click_rows
  FROM (
    SELECT target_path AS name, count(*)::int AS clicks
    FROM analytics_events
    WHERE created_at >= p_since AND event_name = 'click' AND target_path IS NOT NULL
    GROUP BY target_path
    ORDER BY clicks DESC
    LIMIT 20
  ) grouped;

  SELECT COALESCE(jsonb_agg(to_jsonb(grouped) ORDER BY grouped.date), '[]'::jsonb)
  INTO daily_rows
  FROM (
    SELECT to_char(created_at AT TIME ZONE 'Europe/Paris', 'YYYY-MM-DD') AS date,
      count(*) FILTER (WHERE event_name = 'page_view')::int AS views,
      count(*) FILTER (WHERE event_name = 'click')::int AS clicks
    FROM analytics_events
    WHERE created_at >= p_since
    GROUP BY (created_at AT TIME ZONE 'Europe/Paris')::date
  ) grouped;

  SELECT jsonb_build_object(
    'page_views', count(*) FILTER (WHERE event_name = 'page_view'),
    'clicks', count(*) FILTER (WHERE event_name = 'click'),
    'visitors', count(DISTINCT visitor_id) FILTER (WHERE event_name = 'page_view'),
    'sessions', count(DISTINCT session_id) FILTER (WHERE event_name = 'page_view'),
    'sources', source_rows,
    'pages', page_rows,
    'click_targets', click_rows,
    'daily', daily_rows
  ) INTO result
  FROM analytics_events
  WHERE created_at >= p_since;

  RETURN result;
END;
$$;

REVOKE ALL ON FUNCTION public.get_visibility_stats(timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_visibility_stats(timestamptz) TO anon, authenticated;
